[package]
name = "sckitndi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cacao = "0.2"
once_cell = "1"
objc = "0.2.7"
block = "0.1"

[build-dependencies]
bindgen = "0.53.1"
